apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-pod-manager-job
spec:
  template:
    spec:
      containers:
      - name: k8s-pod-manager
        image: your_dockerhub_username/k8s-pod-manager
      restartPolicy: Never
  backoffLimit: 4
